const swisseph = require('swisseph');
const { setAyanamsa } = require('./ayanamsa');
const moment = require('moment-timezone');
swisseph.swe_set_sid_mode(swisseph.SE_SIDM_LAHIRI, 0, 0);
const RASI_NAMES = {ta:['Mesham','Rishabam','Midhunam','Kadagam','Simmam','Kanni','Thulam','Viruchigam','Dhanusu','Magaram','Kumbam','Meenam'],en:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces']};
const NAKSHATRA_NAMES = {ta:['Ashwini','Bharani','Karthigai','Rohini','Mirugasheersham','Thiruvathirai','Punarpoosam','Poosam','Ayilyam','Magam','Pooram','Uthiram','Hastham','Chithirai','Swathi','Visagam','Anusham','Kettai','Moolam','Pooradam','Uthiradam','Thiruvonam','Avittam','Sadhayam','Pooratadhi','Uthiratadhi','Revathi'],en:['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati']};
const PLANETS = [{id:swisseph.SE_SUN,name:'Sun',ta:'Sun'},{id:swisseph.SE_MOON,name:'Moon',ta:'Moon'},{id:swisseph.SE_MARS,name:'Mars',ta:'Mars'},{id:swisseph.SE_MERCURY,name:'Mercury',ta:'Mercury'},{id:swisseph.SE_JUPITER,name:'Jupiter',ta:'Jupiter'},{id:swisseph.SE_VENUS,name:'Venus',ta:'Venus'},{id:swisseph.SE_SATURN,name:'Saturn',ta:'Saturn'},{id:swisseph.SE_MEAN_NODE,name:'Rahu',ta:'Rahu'},{id:swisseph.SE_MEAN_NODE,name:'Ketu',ta:'Ketu',isKetu:true}];
const getJulianDay = (dateStr, timeStr, timezone) => { const dt = moment.tz(dateStr + ' ' + timeStr, 'YYYY-MM-DD HH:mm', timezone); const utc = dt.utc(); const hour = utc.hours() + utc.minutes()/60 + utc.seconds()/3600; return swisseph.swe_julday(utc.year(), utc.month()+1, utc.date(), hour, swisseph.SE_GREG_CAL); };
const getPlanetPosition = (julDay, planetId, isKetu=false) => { const result = swisseph.swe_calc_ut(julDay, planetId, swisseph.SEFLG_SIDEREAL | swisseph.SEFLG_SPEED); let longitude = result.longitude; if(isKetu) longitude = (longitude + 180) % 360; const rasi = Math.floor(longitude/30); const degrees = longitude % 30; const nakshatraIndex = Math.floor(longitude/(360/27)); const pada = Math.floor((longitude % (360/27)) / (360/27/4)) + 1; const isRetrograde = result.longitudeSpeed < 0; return {longitude, rasi, degrees, nakshatraIndex, pada, isRetrograde}; };
const calculatePlanets = (dateStr, timeStr, timezone, lang='ta', ayanamsa='lahiri') => {
  setAyanamsa(ayanamsa); const julDay = getJulianDay(dateStr, timeStr, timezone); const positions = []; for(const planet of PLANETS){ const pos = getPlanetPosition(julDay, planet.id, planet.isKetu||false); positions.push({planet:planet.name,planet_ta:planet.ta,rasi:RASI_NAMES[lang][pos.rasi],rasi_number:pos.rasi+1,degrees:parseFloat(pos.degrees.toFixed(4)),nakshatra:NAKSHATRA_NAMES[lang][pos.nakshatraIndex],pada:pos.pada,is_retrograde:pos.isRetrograde}); } return {julDay, positions}; };
const calculateLagna = (julDay, latitude, longitude, lang='ta') => { const houses = swisseph.swe_houses(julDay, latitude, longitude, 'P'); const lagnaLongitude = houses.ascendant; const rasi = Math.floor(lagnaLongitude/30); const degrees = lagnaLongitude % 30; const nakshatraIndex = Math.floor(lagnaLongitude/(360/27)); return {longitude:lagnaLongitude,rasi:RASI_NAMES[lang][rasi],rasi_number:rasi+1,degrees:parseFloat(degrees.toFixed(4)),nakshatra:NAKSHATRA_NAMES[lang][nakshatraIndex]}; };
module.exports = { calculatePlanets, calculateLagna, getJulianDay, RASI_NAMES, NAKSHATRA_NAMES };
