const swisseph = require('swisseph');
const moment = require('moment-timezone');
const { getJulianDay } = require('../astrology/planets');
const TITHI_NAMES = {en:['Prathama','Dvitiya','Tritiya','Chaturthi','Panchami','Shashthi','Saptami','Ashtami','Navami','Dashami','Ekadashi','Dwadashi','Trayodashi','Chaturdashi','Purnima','Prathama','Dvitiya','Tritiya','Chaturthi','Panchami','Shashthi','Saptami','Ashtami','Navami','Dashami','Ekadashi','Dwadashi','Trayodashi','Chaturdashi','Amavasya'],ta:['Prathama','Dvitiya','Tritiya','Chaturthi','Panchami','Shashthi','Saptami','Ashtami','Navami','Dashami','Ekadashi','Dwadashi','Trayodashi','Chaturdashi','Purnima','Prathama','Dvitiya','Tritiya','Chaturthi','Panchami','Shashthi','Saptami','Ashtami','Navami','Dashami','Ekadashi','Dwadashi','Trayodashi','Chaturdashi','Amavasya']};
const YOGA_NAMES = {en:['Vishkamba','Preeti','Ayushman','Saubhagya','Shobhana','Atiganda','Sukarma','Dhriti','Shula','Ganda','Vriddhi','Dhruva','Vyaghata','Harshana','Vajra','Siddhi','Vyatipata','Variyan','Parigha','Shiva','Siddha','Sadhya','Shubha','Shukla','Brahma','Indra','Vaidhriti'],ta:['Vishkamba','Preeti','Ayushman','Saubhagya','Shobhana','Atiganda','Sukarma','Dhriti','Shula','Ganda','Vriddhi','Dhruva','Vyaghata','Harshana','Vajra','Siddhi','Vyatipata','Variyan','Parigha','Shiva','Siddha','Sadhya','Shubha','Shukla','Brahma','Indra','Vaidhriti']};
const KARANA_NAMES = {en:['Bava','Balava','Kaulava','Taitila','Gara','Vanija','Vishti','Shakuni','Chatushpada','Naga','Kimstughna'],ta:['Bava','Balava','Kaulava','Taitila','Gara','Vanija','Vishti','Shakuni','Chatushpada','Naga','Kimstughna']};
const RAHU_KALAM = {0:[16,30,18,0],1:[7,30,9,0],2:[15,0,16,30],3:[12,0,13,30],4:[10,30,12,0],5:[9,0,10,30],6:[13,30,15,0]};
const YAMAGANDAM = {0:[10,30,12,0],1:[9,0,10,30],2:[7,30,9,0],3:[6,0,7,30],4:[13,30,15,0],5:[15,0,16,30],6:[12,0,13,30]};
const GULIKAI = {0:[6,0,7,30],1:[13,30,15,0],2:[12,0,13,30],3:[10,30,12,0],4:[9,0,10,30],5:[7,30,9,0],6:[6,0,7,30]};
const DAY_NAMES = {en:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],ta:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']};
const toTime = (h) => { const hh = Math.floor(h); const mm = Math.round((h-hh)*60); if(mm===60) return (hh+1).toString().padStart(2,'0')+':00'; return hh.toString().padStart(2,'0')+':'+mm.toString().padStart(2,'0'); };
const getSunriseSunset = (dateStr, latitude, longitude, timezone) => { const julNoon = getJulianDay(dateStr, '12:00', timezone); const sun = swisseph.swe_calc_ut(julNoon, swisseph.SE_SUN, swisseph.SEFLG_SIDEREAL); const lat = latitude * Math.PI/180; const decl = sun.latitude * Math.PI/180; const cosH = -Math.tan(lat)*Math.tan(decl); if(cosH < -1 || cosH > 1) return {sunrise:'06:00',sunset:'18:00'}; const H = Math.acos(cosH)*180/Math.PI; return {sunrise:toTime(12-H/15), sunset:toTime(12+H/15)}; };
const calculateTithi = (sunLong, moonLong) => { let diff = moonLong-sunLong; if(diff<0) diff+=360; return {index:Math.floor(diff/12),degree:diff%12}; };
const calculateYoga = (sunLong, moonLong) => { let sum=(sunLong+moonLong)%360; return {index:Math.floor(sum/(360/27))}; };
const calculateKarana = (sunLong, moonLong) => { let diff=moonLong-sunLong; if(diff<0) diff+=360; return {index:Math.floor(diff/6)%11}; };
const getUpagrahaTime = (table, dayOfWeek, sunrise) => { const t=table[dayOfWeek]; const sh=parseInt(sunrise.split(':')[0]); const sm=parseInt(sunrise.split(':')[1]); const base=sh*60+sm; const start=base+(t[0]-6)*60+t[1]; const end=base+(t[2]-6)*60+t[3]; return {start:toTime(start/60),end:toTime(end/60)}; };
const calculatePanchangam = (dateStr, latitude, longitude, timezone, lang='ta') => {
  const julDay = getJulianDay(dateStr, '06:00', timezone);
  const sun = swisseph.swe_calc_ut(julDay, swisseph.SE_SUN, swisseph.SEFLG_SIDEREAL);
  const moon = swisseph.swe_calc_ut(julDay, swisseph.SE_MOON, swisseph.SEFLG_SIDEREAL);
  const tithi = calculateTithi(sun.longitude, moon.longitude);
  const yoga = calculateYoga(sun.longitude, moon.longitude);
  const karana = calculateKarana(sun.longitude, moon.longitude);
  const nakshatraIndex = Math.floor(moon.longitude/(360/27));
  const dt = moment.tz(dateStr, 'YYYY-MM-DD', timezone);
  const dayOfWeek = dt.day();
  const {sunrise, sunset} = getSunriseSunset(dateStr, latitude, longitude, timezone);
  return { date:dateStr, day:DAY_NAMES[lang][dayOfWeek], tithi:TITHI_NAMES[lang][tithi.index], tithi_number:tithi.index+1, nakshatra_number:nakshatraIndex+1, yoga:YOGA_NAMES[lang][yoga.index], karana:KARANA_NAMES[lang][karana.index], sunrise, sunset, rahu_kalam:getUpagrahaTime(RAHU_KALAM,dayOfWeek,sunrise), yamagandam:getUpagrahaTime(YAMAGANDAM,dayOfWeek,sunrise), gulikai:getUpagrahaTime(GULIKAI,dayOfWeek,sunrise) };
};
module.exports = { calculatePanchangam, TITHI_NAMES, YOGA_NAMES, KARANA_NAMES, DAY_NAMES };
